import assert from 'node:assert/strict';
import test from 'node:test';

import {
  createCoordinatorGithubSideEffects,
  createGhPullRequestClient,
  createGitBranchClient,
} from '../src/coordinator-github-side-effects.mjs';
import { createRunEventLog } from '../src/run-evidence.mjs';

test('coordinator posts progress, pushes branch, opens linked PR, and records PR run events', async () => {
  const comments = [];
  const pushes = [];
  const prs = [];
  const runEvents = createRunEventLog({ async appendText() {} });
  const sideEffects = createCoordinatorGithubSideEffects({
    issueClient: {
      async createComment(comment) {
        comments.push(comment);
        return { url: `https://github.com/justbill2020/Lambchop/issues/${comment.issueNumber}#comment-${comments.length}` };
      },
    },
    gitClient: {
      async pushBranch(push) {
        pushes.push(push);
        return { remoteBranch: `origin/${push.branch}` };
      },
    },
    pullRequestClient: {
      async createPullRequest(pr) {
        prs.push(pr);
        return {
          number: 88,
          url: 'https://github.com/justbill2020/Lambchop/pull/88',
          state: 'OPEN',
        };
      },
    },
    runEventLog: runEvents,
  });

  const result = await sideEffects.publishCompletedRun({
    repository: 'justbill2020/Lambchop',
    issueNumber: 53,
    runId: 'run-53',
    branch: 'codex/lambchop-issue-53',
    baseBranch: 'main',
    title: 'Add GitHub issue comments, branch push, and linked PR loop',
    summary: 'Completed coordinator side-effect loop.',
    validation: {
      status: 'passed',
      commands: ['node --test tests/coordinator-github-side-effects.test.mjs'],
    },
    changedFiles: ['src/coordinator-github-side-effects.mjs'],
    allowPush: true,
    allowPullRequest: true,
    autoMerge: false,
  });

  assert.deepEqual(pushes, [
    {
      repository: 'justbill2020/Lambchop',
      branch: 'codex/lambchop-issue-53',
    },
  ]);
  assert.equal(prs.length, 1);
  assert.equal(prs[0].repository, 'justbill2020/Lambchop');
  assert.equal(prs[0].headBranch, 'codex/lambchop-issue-53');
  assert.equal(prs[0].baseBranch, 'main');
  assert.match(prs[0].body, /Closes #53/);
  assert.match(prs[0].body, /Auto-merge: disabled/);
  assert.equal(result.status, 'pr-opened');
  assert.equal(result.pullRequest.url, 'https://github.com/justbill2020/Lambchop/pull/88');
  assert.deepEqual(comments.map((comment) => comment.issueNumber), [53, 53, 53]);
  assert.match(comments[0].body, /^> \*This was generated by AI during triage\.\*/);
  assert.match(comments[0].body, /Work started/);
  assert.match(comments[1].body, /Validation passed/);
  assert.match(comments[2].body, /Pull request opened/);
  assert.deepEqual(runEvents.events().map((event) => event.type), [
    'comment',
    'validation.passed',
    'comment',
    'pr',
    'comment',
  ]);
});

test('coordinator records actionable blockers when publishing is not allowed', async () => {
  const comments = [];
  const runEvents = createRunEventLog({ async appendText() {} });
  const sideEffects = createCoordinatorGithubSideEffects({
    issueClient: {
      async createComment(comment) {
        comments.push(comment);
        return { url: `https://github.com/justbill2020/Lambchop/issues/${comment.issueNumber}#blocked` };
      },
    },
    gitClient: {
      async pushBranch() {
        throw new Error('pushBranch must not be called when allowPush=false');
      },
    },
    pullRequestClient: {
      async createPullRequest() {
        throw new Error('createPullRequest must not be called when allowPullRequest=false');
      },
    },
    runEventLog: runEvents,
  });

  const result = await sideEffects.publishCompletedRun({
    repository: 'justbill2020/Lambchop',
    issueNumber: 53,
    runId: 'run-53-blocked',
    branch: 'codex/lambchop-issue-53',
    baseBranch: 'main',
    title: 'Add GitHub issue comments, branch push, and linked PR loop',
    summary: 'Completed coordinator side-effect loop.',
    validation: {
      status: 'passed',
      commands: ['node --test tests/coordinator-github-side-effects.test.mjs'],
    },
    changedFiles: ['src/coordinator-github-side-effects.mjs'],
    allowPush: false,
    allowPullRequest: false,
    autoMerge: true,
  });

  assert.equal(result.status, 'blocked');
  assert.deepEqual(result.blockers, [
    {
      type: 'push-disabled',
      message: 'Branch push is not allowed by coordinator policy.',
      nextStep: 'Enable push policy for this run or keep the branch local.',
    },
  ]);
  assert.equal(result.autoMerge, false);
  assert.equal(comments.length, 3);
  assert.match(comments.at(-1).body, /## Blocked/);
  assert.match(comments.at(-1).body, /Branch push is not allowed/);
  assert.deepEqual(runEvents.events().map((event) => event.type), [
    'comment',
    'validation.passed',
    'comment',
    'blocker',
    'comment',
  ]);
});

test('coordinator records failed push or PR operations as blockers', async () => {
  const comments = [];
  const runEvents = createRunEventLog({ async appendText() {} });
  const sideEffects = createCoordinatorGithubSideEffects({
    issueClient: {
      async createComment(comment) {
        comments.push(comment);
        return { url: `https://github.com/justbill2020/Lambchop/issues/${comment.issueNumber}#failed` };
      },
    },
    gitClient: {
      async pushBranch() {
        throw new Error('remote rejected branch');
      },
    },
    pullRequestClient: {
      async createPullRequest() {
        throw new Error('createPullRequest must not run after push failure');
      },
    },
    runEventLog: runEvents,
  });

  const result = await sideEffects.publishCompletedRun({
    repository: 'justbill2020/Lambchop',
    issueNumber: 53,
    runId: 'run-53-push-failed',
    branch: 'codex/lambchop-issue-53',
    title: 'Add GitHub issue comments, branch push, and linked PR loop',
    summary: 'Completed coordinator side-effect loop.',
    validation: {
      status: 'passed',
      commands: ['node --test tests/coordinator-github-side-effects.test.mjs'],
    },
    changedFiles: ['src/coordinator-github-side-effects.mjs'],
    allowPush: true,
    allowPullRequest: true,
    autoMerge: false,
  });

  assert.equal(result.status, 'blocked');
  assert.equal(result.blockers[0].type, 'push-failed');
  assert.match(result.blockers[0].message, /remote rejected branch/);
  assert.match(result.blockers[0].nextStep, /Inspect Git credentials/);
  assert.match(comments.at(-1).body, /remote rejected branch/);
  assert.deepEqual(runEvents.events().map((event) => event.type), [
    'comment',
    'validation.passed',
    'comment',
    'blocker',
    'comment',
  ]);
});

test('production Git and PR clients use non-merging push and gh pr create commands', async () => {
  const gitCalls = [];
  const ghCalls = [];
  const gitClient = createGitBranchClient({
    async runGit(args) {
      gitCalls.push(args);
      return '';
    },
  });
  const prClient = createGhPullRequestClient({
    async runGh(args, options) {
      ghCalls.push({ args, options });
      return 'https://github.com/justbill2020/Lambchop/pull/88';
    },
  });

  await gitClient.pushBranch({
    repository: 'justbill2020/Lambchop',
    branch: 'codex/lambchop-issue-53',
  });
  const pr = await prClient.createPullRequest({
    repository: 'justbill2020/Lambchop',
    title: 'Add GitHub issue comments, branch push, and linked PR loop',
    headBranch: 'codex/lambchop-issue-53',
    baseBranch: 'main',
    body: 'Closes #53',
  });

  assert.deepEqual(gitCalls, [[
    'push',
    '--set-upstream',
    'origin',
    'codex/lambchop-issue-53',
  ]]);
  assert.deepEqual(ghCalls, [{
    args: [
      'pr',
      'create',
      '--repo',
      'justbill2020/Lambchop',
      '--title',
      'Add GitHub issue comments, branch push, and linked PR loop',
      '--head',
      'codex/lambchop-issue-53',
      '--base',
      'main',
      '--body-file',
      '-',
      '--json',
      'number,url,state',
    ],
    options: { input: 'Closes #53' },
  }]);
  assert.deepEqual(pr, {
    number: 88,
    url: 'https://github.com/justbill2020/Lambchop/pull/88',
    state: 'OPEN',
  });
});
