import assert from 'node:assert/strict';
import test from 'node:test';

import { createGhIssueClient } from '../src/github-issue-client.mjs';

test('gh issue client lists issues with the fields needed by the MVP planner', async () => {
  const calls = [];
  const client = createGhIssueClient({
    async runGh(args) {
      calls.push(args);
      return JSON.stringify([
        {
          number: 43,
          title: 'Bootstrap Lambchop-operated MVP planning loop',
          state: 'OPEN',
          labels: [{ name: 'ready-for-agent' }],
          body: '## Parent\n\n#42',
          url: 'https://github.com/justbill2020/Lambchop/issues/43',
        },
      ]);
    },
  });

  const issues = await client.listIssues({
    repository: 'justbill2020/Lambchop',
    state: 'all',
  });

  assert.deepEqual(calls, [[
    'issue',
    'list',
    '--repo',
    'justbill2020/Lambchop',
    '--state',
    'all',
    '--limit',
    '200',
    '--json',
    'number,title,state,labels,body,url',
  ]]);
  assert.equal(issues[0].number, 43);
  assert.equal(issues[0].labels[0].name, 'ready-for-agent');
});

test('gh issue client posts planning comments to the goal issue', async () => {
  const calls = [];
  const client = createGhIssueClient({
    async runGh(args, options) {
      calls.push({ args, options });
      return 'https://github.com/justbill2020/Lambchop/issues/42#issuecomment-1';
    },
  });

  const result = await client.createComment({
    repository: 'justbill2020/Lambchop',
    issueNumber: 42,
    body: '> *This was generated by AI during triage.*\n\n## MVP planning status',
  });

  assert.equal(result.url, 'https://github.com/justbill2020/Lambchop/issues/42#issuecomment-1');
  assert.deepEqual(calls, [{
    args: [
      'issue',
      'comment',
      '42',
      '--repo',
      'justbill2020/Lambchop',
      '--body-file',
      '-',
    ],
    options: {
      input: '> *This was generated by AI during triage.*\n\n## MVP planning status',
    },
  }]);
});

test('gh issue client reads issue comments for feedback intake', async () => {
  const calls = [];
  const client = createGhIssueClient({
    async runGh(args) {
      calls.push(args);
      return JSON.stringify({
        comments: [
          {
            id: 'comment-1',
            url: 'https://github.com/justbill2020/Lambchop/issues/42#issuecomment-1',
            author: { login: 'justbill2020' },
            body: '/lambchop-feedback\nintent: retry',
            createdAt: '2026-06-23T22:00:00Z',
          },
        ],
      });
    },
  });

  const comments = await client.listComments({
    repository: 'justbill2020/Lambchop',
    issueNumber: 42,
  });

  assert.deepEqual(calls, [[
    'issue',
    'view',
    '42',
    '--repo',
    'justbill2020/Lambchop',
    '--comments',
    '--json',
    'comments',
  ]]);
  assert.equal(comments[0].id, 'comment-1');
  assert.equal(comments[0].body, '/lambchop-feedback\nintent: retry');
});
