import assert from 'node:assert/strict';
import test from 'node:test';

import { createMvpPlanningLoop } from '../src/mvp-planning-loop.mjs';

const readyForAgent = [{ name: 'ready-for-agent' }];
const readyForHuman = [{ name: 'ready-for-human' }];

test('MVP planning loop derives the active goal, children, next issue, blockers, and dashboard status from GitHub issues', () => {
  const planner = createMvpPlanningLoop();
  const issues = [
    {
      number: 42,
      title: 'Dogfood Lambchop as the first managed AI engineering project',
      state: 'OPEN',
      labels: readyForAgent,
      body: '## What to build\nParent goal.',
      url: 'https://github.com/justbill2020/Lambchop/issues/42',
    },
    {
      number: 43,
      title: 'Bootstrap Lambchop-operated MVP planning loop',
      state: 'CLOSED',
      labels: readyForAgent,
      body: '## Parent\n\n#42\n\n## Blocked by\n\nNone - can start immediately',
      url: 'https://github.com/justbill2020/Lambchop/issues/43',
    },
    {
      number: 44,
      title: 'Add Lambchop feedback intake and decision queue',
      state: 'OPEN',
      labels: readyForAgent,
      body: '## Parent\n\n#42\n\n## Blocked by\n\n- #43',
      url: 'https://github.com/justbill2020/Lambchop/issues/44',
    },
    {
      number: 45,
      title: 'Create standalone coordinator CLI skeleton',
      state: 'OPEN',
      labels: readyForAgent,
      body: '## Parent\n\n#42\n\n## Blocked by\n\n- #43\n- #44',
      url: 'https://github.com/justbill2020/Lambchop/issues/45',
    },
    {
      number: 48,
      title: 'Add machine peer registry and heartbeat for dogfood runners',
      state: 'OPEN',
      labels: readyForAgent,
      body: '## Parent\n\n#42\n\n## Blocked by\n\n- #45',
      url: 'https://github.com/justbill2020/Lambchop/issues/48',
    },
    {
      number: 33,
      title: 'Define canonical runtime state vs orchestration-view projection',
      state: 'OPEN',
      labels: readyForHuman,
      body: '## Parent\n\n#34',
      url: 'https://github.com/justbill2020/Lambchop/issues/33',
    },
  ];

  const plan = planner.plan({ goalIssueNumber: 42, issues });

  assert.equal(plan.activeGoal.number, 42);
  assert.deepEqual(
    plan.childIssues.map((issue) => issue.number),
    [43, 44, 45, 48],
  );
  assert.equal(plan.nextIssue.number, 44);
  assert.deepEqual(plan.blockedIssues.map((issue) => issue.number), [45, 48]);
  assert.deepEqual(plan.parallelizableCandidates.map((issue) => issue.number), [44]);
  assert.deepEqual(plan.status, {
    active_goal: {
      number: 42,
      title: 'Dogfood Lambchop as the first managed AI engineering project',
      url: 'https://github.com/justbill2020/Lambchop/issues/42',
    },
    next_issue: {
      number: 44,
      title: 'Add Lambchop feedback intake and decision queue',
      url: 'https://github.com/justbill2020/Lambchop/issues/44',
    },
    counts: {
      child_issues: 4,
      ready: 1,
      blocked: 2,
      done: 1,
      human: 0,
    },
    blockers: [
      {
        number: 45,
        title: 'Create standalone coordinator CLI skeleton',
        blocked_by: [44],
      },
      {
        number: 48,
        title: 'Add machine peer registry and heartbeat for dogfood runners',
        blocked_by: [45],
      },
    ],
    parallelizable_candidates: [
      {
        number: 44,
        title: 'Add Lambchop feedback intake and decision queue',
        url: 'https://github.com/justbill2020/Lambchop/issues/44',
      },
    ],
    source: 'github-issues',
    bootstrap_context: 'chat-derived plan is now represented by GitHub issues',
  });
});

test('MVP planning loop formats a durable AI triage planning comment for the goal issue', () => {
  const planner = createMvpPlanningLoop();
  const plan = planner.plan({
    goalIssueNumber: 42,
    issues: [
      {
        number: 42,
        title: 'Dogfood Lambchop as the first managed AI engineering project',
        state: 'OPEN',
        labels: readyForAgent,
        body: '## What to build\nParent goal.',
        url: 'https://github.com/justbill2020/Lambchop/issues/42',
      },
      {
        number: 43,
        title: 'Bootstrap Lambchop-operated MVP planning loop',
        state: 'OPEN',
        labels: readyForAgent,
        body: '## Parent\n\n#42\n\n## Blocked by\n\nNone - can start immediately',
        url: 'https://github.com/justbill2020/Lambchop/issues/43',
      },
    ],
  });

  assert.equal(
    planner.formatPlanningComment(plan),
    [
      '> *This was generated by AI during triage.*',
      '',
      '## MVP planning status',
      '',
      '- Active goal: #42 Dogfood Lambchop as the first managed AI engineering project',
      '- Next issue: #43 Bootstrap Lambchop-operated MVP planning loop',
      '- Ready candidates: #43',
      '- Blocked issues: none',
      '- Done child issues: 0',
      '',
      'Bootstrap note: chat-derived planning context has been moved into GitHub Issues and Lambchop planning output.',
    ].join('\n'),
  );
});

test('MVP planning loop loads the active goal and children through a GitHub issue client', async () => {
  const calls = [];
  const planner = createMvpPlanningLoop({
    issueClient: {
      async listIssues({ repository, state }) {
        calls.push({ fn: 'listIssues', repository, state });
        return [
          {
            number: 42,
            title: 'Dogfood Lambchop as the first managed AI engineering project',
            state: 'OPEN',
            labels: readyForAgent,
            body: '## What to build\nParent goal.',
            url: 'https://github.com/justbill2020/Lambchop/issues/42',
          },
          {
            number: 43,
            title: 'Bootstrap Lambchop-operated MVP planning loop',
            state: 'OPEN',
            labels: readyForAgent,
            body: '## Parent\n\n#42\n\n## Blocked by\n\nNone - can start immediately',
            url: 'https://github.com/justbill2020/Lambchop/issues/43',
          },
        ];
      },
    },
  });

  const plan = await planner.planFromGithub({
    repository: 'justbill2020/Lambchop',
    goalIssueNumber: 42,
  });

  assert.deepEqual(calls, [
    { fn: 'listIssues', repository: 'justbill2020/Lambchop', state: 'all' },
  ]);
  assert.equal(plan.activeGoal.number, 42);
  assert.equal(plan.nextIssue.number, 43);
  assert.equal(plan.status.source, 'github-issues');
});

test('MVP planning loop parses structured dependency references from issue comments', () => {
  const planner = createMvpPlanningLoop();
  const plan = planner.plan({
    goalIssueNumber: 42,
    issues: [
      {
        number: 42,
        title: 'Dogfood Lambchop as the first managed AI engineering project',
        state: 'OPEN',
        labels: readyForAgent,
        body: '## What to build\nParent goal.',
        url: 'https://github.com/justbill2020/Lambchop/issues/42',
      },
      {
        number: 47,
        title: 'Implement GitHub Issues intake and coordinator assignment leases',
        state: 'OPEN',
        labels: readyForAgent,
        body: '## Parent\n\n#42\n\n## Blocked by\n\nNone - can start immediately',
        comments: [
          {
            body: [
              '/lambchop-dependency',
              'blocked-by: #46',
              'reason: managed project registry must exist first',
            ].join('\n'),
          },
          {
            body: 'Ordinary comment mentioning #999 should not become a dependency.',
          },
        ],
        url: 'https://github.com/justbill2020/Lambchop/issues/47',
      },
      {
        number: 46,
        title: 'Register Lambchop as the first managed project',
        state: 'OPEN',
        labels: readyForAgent,
        body: '## Parent\n\n#42',
        url: 'https://github.com/justbill2020/Lambchop/issues/46',
      },
    ],
  });

  assert.deepEqual(plan.blockedIssues.map((issue) => ({
    number: issue.number,
    blockedBy: issue.unresolvedBlockers,
  })), [
    {
      number: 47,
      blockedBy: [46],
    },
  ]);
  assert.deepEqual(plan.parallelizableCandidates.map((issue) => issue.number), [46]);
});

test('MVP planning loop posts durable planning status through a GitHub issue client', async () => {
  const comments = [];
  const planner = createMvpPlanningLoop({
    issueClient: {
      async createComment({ repository, issueNumber, body }) {
        comments.push({ repository, issueNumber, body });
        return {
          url: `https://github.com/justbill2020/Lambchop/issues/${issueNumber}#issuecomment-1`,
        };
      },
    },
  });
  const plan = planner.plan({
    goalIssueNumber: 42,
    issues: [
      {
        number: 42,
        title: 'Dogfood Lambchop as the first managed AI engineering project',
        state: 'OPEN',
        labels: readyForAgent,
        body: '## What to build\nParent goal.',
        url: 'https://github.com/justbill2020/Lambchop/issues/42',
      },
      {
        number: 43,
        title: 'Bootstrap Lambchop-operated MVP planning loop',
        state: 'OPEN',
        labels: readyForAgent,
        body: '## Parent\n\n#42\n\n## Blocked by\n\nNone - can start immediately',
        url: 'https://github.com/justbill2020/Lambchop/issues/43',
      },
    ],
  });

  const result = await planner.postPlanningComment({
    repository: 'justbill2020/Lambchop',
    plan,
  });

  assert.equal(result.url, 'https://github.com/justbill2020/Lambchop/issues/42#issuecomment-1');
  assert.equal(comments.length, 1);
  assert.equal(comments[0].repository, 'justbill2020/Lambchop');
  assert.equal(comments[0].issueNumber, 42);
  assert.match(comments[0].body, /^> \*This was generated by AI during triage\.\*/);
  assert.match(comments[0].body, /Next issue: #43/);
});
