import assert from 'node:assert/strict';
import test from 'node:test';

import { createPrAuthorizationIntake } from '../src/pr-authorization-intake.mjs';

test('PR authorization intake converts an approval feedback comment into a one-run PR override', () => {
  const intake = createPrAuthorizationIntake();

  const authorization = intake.fromComments({
    issueNumber: 55,
    comments: [
      {
        id: 'comment-1',
        url: 'https://github.com/justbill2020/Lambchop/issues/55#issuecomment-1',
        author: { login: 'justbill2020' },
        body: [
          '/lambchop-feedback',
          'intent: approve',
          'target: #55',
          'message: allow one coordinator-owned linked PR for the dogfood proof; auto-merge remains disabled.',
        ].join('\n'),
        createdAt: '2026-06-23T23:45:00Z',
      },
    ],
  });

  assert.deepEqual(authorization, {
    status: 'authorized',
    issue_number: 55,
    capability: 'open-linked-pr',
    may_open_pr: true,
    auto_merge: false,
    source_comment_url: 'https://github.com/justbill2020/Lambchop/issues/55#issuecomment-1',
    authorized_by: 'justbill2020',
    authorized_at: '2026-06-23T23:45:00Z',
    scope: 'single-dogfood-proof-run',
  });
});

test('PR authorization intake ignores unrelated approval feedback', () => {
  const authorization = createPrAuthorizationIntake().fromComments({
    issueNumber: 55,
    comments: [
      {
        body: [
          '/lambchop-feedback',
          'intent: approve',
          'target: #54',
          'message: approve the dashboard slice.',
        ].join('\n'),
      },
    ],
  });

  assert.deepEqual(authorization, {
    status: 'not-authorized',
    issue_number: 55,
    capability: 'open-linked-pr',
    may_open_pr: false,
    auto_merge: false,
  });
});

test('PR authorization intake ignores approval snippets embedded in AI triage comments', () => {
  const authorization = createPrAuthorizationIntake().fromComments({
    issueNumber: 55,
    comments: [
      {
        body: [
          '> *This was generated by AI during triage.*',
          '',
          'Dashboard-visible approval packet:',
          '```text',
          '/lambchop-feedback',
          'intent: approve',
          'target: #55',
          'message: allow one coordinator-owned linked PR for the dogfood proof; auto-merge remains disabled.',
          '```',
        ].join('\n'),
      },
    ],
  });

  assert.deepEqual(authorization, {
    status: 'not-authorized',
    issue_number: 55,
    capability: 'open-linked-pr',
    may_open_pr: false,
    auto_merge: false,
  });
});

test('PR authorization intake accepts direct feedback commands only after optional whitespace', () => {
  const authorization = createPrAuthorizationIntake().fromComments({
    issueNumber: 55,
    comments: [
      {
        url: 'https://github.com/justbill2020/Lambchop/issues/55#issuecomment-direct',
        author: { login: 'justbill2020' },
        body: [
          '',
          '/lambchop-feedback',
          'intent: approve',
          'target: #55',
          'message: allow one coordinator-owned linked PR for the dogfood proof; auto-merge remains disabled.',
        ].join('\n'),
        createdAt: '2026-06-24T00:00:00Z',
      },
    ],
  });

  assert.equal(authorization.status, 'authorized');
  assert.equal(authorization.source_comment_url, 'https://github.com/justbill2020/Lambchop/issues/55#issuecomment-direct');
});

test('PR authorization intake can read issue comments through an issue client', async () => {
  const calls = [];
  const authorization = await createPrAuthorizationIntake({
    issueClient: {
      async listComments({ repository, issueNumber }) {
        calls.push({ repository, issueNumber });
        return [
          {
            url: 'https://github.com/justbill2020/Lambchop/issues/55#issuecomment-2',
            author: { login: 'justbill2020' },
            body: [
              '/lambchop-feedback',
              'intent: approve',
              'target: #55',
              'message: allow one coordinator-owned linked PR for the dogfood proof; auto-merge remains disabled.',
            ].join('\n'),
            createdAt: '2026-06-24T00:00:00Z',
          },
        ];
      },
    },
  }).fromGithub({
    repository: 'justbill2020/Lambchop',
    issueNumber: 55,
  });

  assert.deepEqual(calls, [{ repository: 'justbill2020/Lambchop', issueNumber: 55 }]);
  assert.equal(authorization.status, 'authorized');
  assert.equal(authorization.source_comment_url, 'https://github.com/justbill2020/Lambchop/issues/55#issuecomment-2');
});
