import assert from 'node:assert/strict';
import test from 'node:test';

import { createGhPullRequestClient } from '../src/coordinator-github-side-effects.mjs';
import { createPrOwnershipLoop } from '../src/pr-ownership-loop.mjs';
import { createRunEventLog } from '../src/run-evidence.mjs';

test('PR ownership loop schedules a same-lineage repair run when CI fails', async () => {
  const comments = [];
  const runEvents = createRunEventLog({
    async appendText() {},
    now: (() => {
      const times = [
        '2026-06-23T23:55:00.000Z',
        '2026-06-23T23:56:00.000Z',
      ];
      return () => times.shift() ?? '2026-06-23T23:57:00.000Z';
    })(),
  });
  const loop = createPrOwnershipLoop({
    issueClient: {
      async createComment(comment) {
        comments.push(comment);
        return { url: `https://github.com/justbill2020/Lambchop/issues/${comment.issueNumber}#repair` };
      },
    },
    pullRequestClient: {
      async viewPullRequest({ repository, number }) {
        assert.equal(repository, 'justbill2020/Lambchop');
        assert.equal(number, 90);
        return {
          number: 90,
          url: 'https://github.com/justbill2020/Lambchop/pull/90',
          state: 'OPEN',
          mergeStateStatus: 'UNSTABLE',
          reviewDecision: '',
          statusCheckRollup: [
            {
              name: 'test',
              status: 'COMPLETED',
              conclusion: 'FAILURE',
              detailsUrl: 'https://github.com/justbill2020/Lambchop/actions/runs/1',
            },
          ],
        };
      },
    },
    runEventLog: runEvents,
  });

  const result = await loop.observePullRequest({
    repository: 'justbill2020/Lambchop',
    issueNumber: 40,
    runId: 'run-40',
    pullRequestNumber: 90,
  });

  assert.equal(result.status, 'repair-scheduled');
  assert.deepEqual(result.repair, {
    run_id: 'run-40-repair-1',
    parent_run_id: 'run-40',
    issue_number: 40,
    pull_request: {
      number: 90,
      url: 'https://github.com/justbill2020/Lambchop/pull/90',
    },
    reason: 'ci-failed',
    summary: 'CI check failed: test.',
  });
  assert.deepEqual(runEvents.events().map((event) => event.type), [
    'pr.observed',
    'repair.scheduled',
  ]);
  assert.equal(comments.length, 1);
  assert.match(comments[0].body, /^> \*This was generated by AI during triage\.\*/);
  assert.match(comments[0].body, /## Repair scheduled/);
  assert.match(comments[0].body, /CI check failed: test/);
});

test('PR ownership loop schedules repair when review changes are requested', async () => {
  const comments = [];
  const runEvents = createRunEventLog({ async appendText() {} });
  const loop = createPrOwnershipLoop({
    issueClient: {
      async createComment(comment) {
        comments.push(comment);
        return { url: `https://github.com/justbill2020/Lambchop/issues/${comment.issueNumber}#review` };
      },
    },
    pullRequestClient: {
      async viewPullRequest() {
        return {
          number: 91,
          url: 'https://github.com/justbill2020/Lambchop/pull/91',
          state: 'OPEN',
          mergeStateStatus: 'CLEAN',
          reviewDecision: 'CHANGES_REQUESTED',
          statusCheckRollup: [
            { name: 'test', status: 'COMPLETED', conclusion: 'SUCCESS' },
          ],
        };
      },
    },
    runEventLog: runEvents,
  });

  const result = await loop.observePullRequest({
    repository: 'justbill2020/Lambchop',
    issueNumber: 40,
    runId: 'run-40',
    pullRequestNumber: 91,
  });

  assert.equal(result.status, 'repair-scheduled');
  assert.equal(result.repair.reason, 'review-changes-requested');
  assert.equal(result.repair.summary, 'Review requested changes.');
  assert.match(comments[0].body, /Review requested changes/);
});

test('PR ownership loop marks clean approved PRs merge-ready without auto-merge', async () => {
  const comments = [];
  const runEvents = createRunEventLog({ async appendText() {} });
  const loop = createPrOwnershipLoop({
    issueClient: {
      async createComment(comment) {
        comments.push(comment);
        return { url: `https://github.com/justbill2020/Lambchop/issues/${comment.issueNumber}#ready` };
      },
    },
    pullRequestClient: {
      async viewPullRequest() {
        return {
          number: 92,
          url: 'https://github.com/justbill2020/Lambchop/pull/92',
          state: 'OPEN',
          mergeStateStatus: 'CLEAN',
          reviewDecision: 'APPROVED',
          statusCheckRollup: [
            { name: 'test', status: 'COMPLETED', conclusion: 'SUCCESS' },
          ],
        };
      },
    },
    runEventLog: runEvents,
  });

  const result = await loop.observePullRequest({
    repository: 'justbill2020/Lambchop',
    issueNumber: 40,
    runId: 'run-40',
    pullRequestNumber: 92,
  });

  assert.equal(result.status, 'merge-ready');
  assert.equal(result.auto_merge, false);
  assert.deepEqual(runEvents.events().map((event) => event.type), [
    'pr.observed',
    'pr.merge-ready',
  ]);
  assert.match(comments[0].body, /## Merge ready/);
  assert.match(comments[0].body, /Auto-merge: disabled/);
});

test('production PR client reads CI and review state through gh pr view', async () => {
  const ghCalls = [];
  const client = createGhPullRequestClient({
    async runGh(args) {
      ghCalls.push(args);
      return JSON.stringify({
        number: 92,
        url: 'https://github.com/justbill2020/Lambchop/pull/92',
        state: 'OPEN',
        mergeStateStatus: 'CLEAN',
        reviewDecision: 'APPROVED',
        statusCheckRollup: [],
      });
    },
  });

  const pr = await client.viewPullRequest({
    repository: 'justbill2020/Lambchop',
    number: 92,
  });

  assert.deepEqual(ghCalls, [[
    'pr',
    'view',
    '92',
    '--repo',
    'justbill2020/Lambchop',
    '--json',
    'number,url,state,mergedAt,mergeStateStatus,reviewDecision,statusCheckRollup',
  ]]);
  assert.equal(pr.mergeStateStatus, 'CLEAN');
  assert.equal(pr.reviewDecision, 'APPROVED');
});

test('PR ownership loop records merged PRs as terminal completion', async () => {
  const comments = [];
  const runEvents = createRunEventLog({ async appendText() {} });
  const loop = createPrOwnershipLoop({
    issueClient: {
      async createComment(comment) {
        comments.push(comment);
        return { url: `https://github.com/justbill2020/Lambchop/issues/${comment.issueNumber}#merged` };
      },
    },
    pullRequestClient: {
      async viewPullRequest() {
        return {
          number: 93,
          url: 'https://github.com/justbill2020/Lambchop/pull/93',
          state: 'MERGED',
          mergedAt: '2026-06-23T23:58:00Z',
          mergeStateStatus: 'UNKNOWN',
          reviewDecision: '',
          statusCheckRollup: [],
        };
      },
    },
    runEventLog: runEvents,
  });

  const result = await loop.observePullRequest({
    repository: 'justbill2020/Lambchop',
    issueNumber: 40,
    runId: 'run-40',
    pullRequestNumber: 93,
  });

  assert.equal(result.status, 'merged');
  assert.deepEqual(runEvents.events().map((event) => event.type), [
    'pr.observed',
    'completion',
  ]);
  assert.match(comments[0].body, /## Pull request merged/);
  assert.match(comments[0].body, /Issue closure should be handled by GitHub linking/);
});
