import assert from 'node:assert/strict';
import test from 'node:test';

import { createRunEventLog } from '../src/run-evidence.mjs';

test('run event log appends ordered events and references per-run OFK work logs', async () => {
  const writes = [];
  const log = createRunEventLog({
    async appendText(path, text) {
      writes.push({ path, text });
    },
    now: (() => {
      const times = [
        '2026-06-23T23:10:00.000Z',
        '2026-06-23T23:11:00.000Z',
        '2026-06-23T23:12:00.000Z',
      ];
      return () => times.shift() ?? '2026-06-23T23:13:00.000Z';
    })(),
  });

  await log.append({
    runId: 'run-52',
    type: 'selection',
    summary: 'Selected issue #52 for run logging.',
    workLogEntry: 'Selected #52 after #50 enabled worker contracts.',
  });
  await log.append({
    runId: 'run-52',
    type: 'worker.completed',
    summary: 'Fake worker completed run logging slice.',
    changedFiles: ['src/run-evidence.mjs', 'tests/run-event-log.test.mjs'],
  });
  await log.append({
    runId: 'run-52',
    type: 'validation.passed',
    summary: 'Focused run-event tests passed.',
    validation: {
      status: 'passed',
      commands: ['node --test tests/run-event-log.test.mjs'],
    },
  });

  assert.deepEqual(log.events().map((event) => [event.sequence, event.type]), [
    [1, 'selection'],
    [2, 'worker.completed'],
    [3, 'validation.passed'],
  ]);
  assert.equal(log.events()[0].work_log_path, 'runs/run-52/work-log.md');
  assert.deepEqual(writes, [
    {
      path: 'runs/run-52/work-log.md',
      text: '- 2026-06-23T23:10:00.000Z: Selected #52 after #50 enabled worker contracts.\n',
    },
  ]);
});

test('run event log creates compact GitHub-ready summaries and analytics v0', async () => {
  const log = createRunEventLog({
    async appendText() {},
    now: (() => {
      const times = [
        '2026-06-23T23:20:00.000Z',
        '2026-06-23T23:21:00.000Z',
        '2026-06-23T23:22:00.000Z',
        '2026-06-23T23:23:00.000Z',
      ];
      return () => times.shift() ?? '2026-06-23T23:24:00.000Z';
    })(),
  });

  await log.append({
    runId: 'run-52',
    type: 'assignment',
    summary: 'Assigned #52 to bill-windows.',
  });
  await log.append({
    runId: 'run-52',
    type: 'blocker',
    summary: 'Validation command failed once before fix.',
    blocker: {
      reason: 'missing module export',
    },
  });
  await log.append({
    runId: 'run-52',
    type: 'files.changed',
    summary: 'Changed run evidence files.',
    changedFiles: ['src/run-evidence.mjs', 'tests/run-event-log.test.mjs'],
  });
  await log.append({
    runId: 'run-52',
    type: 'completion',
    summary: 'Completed append-only run event log MVP.',
    validation: {
      status: 'passed',
      commands: ['node --test tests/run-event-log.test.mjs'],
    },
  });

  assert.equal(log.summarizeForIssueComment({ runId: 'run-52' }), [
    '> *This was generated by AI during triage.*',
    '',
    '## Run run-52 Summary',
    '',
    '- Events: 4',
    '- Latest status: Completed append-only run event log MVP.',
    '- Validation: passed',
    '- Changed files: src/run-evidence.mjs, tests/run-event-log.test.mjs',
    '- Blockers: 1',
    '- Work log: not recorded',
  ].join('\n'));
  assert.deepEqual(log.sessionAnalytics({ runId: 'run-52' }), {
    run_id: 'run-52',
    event_count: 4,
    blocker_count: 1,
    changed_file_count: 2,
    validation_status: 'passed',
    churn_signals: {
      repeated_blockers: 1,
      changed_files: 2,
    },
  });
});
