const FEEDBACK_MARKER = '/lambchop-feedback';

const VALID_INTENTS = new Set([
  'approve',
  'reject',
  'revise',
  'pause',
  'resume',
  'retry',
  'reassign',
  'escalate',
  'tighten-policy',
  'loosen-policy',
]);

function authorLogin(comment) {
  return comment.author?.login ?? comment.author ?? null;
}

function parseFields(body) {
  const fields = {};
  for (const line of body.split(/\r?\n/)) {
    const match = line.match(/^(?<key>[A-Za-z_-]+):\s*(?<value>.*)$/);
    if (match) {
      fields[match.groups.key.toLowerCase()] = match.groups.value.trim();
    }
  }
  return fields;
}

function parseTargetIssue(value) {
  const match = String(value ?? '').match(/#(\d+)/);
  return match ? Number(match[1]) : null;
}

function feedbackKey(comment) {
  return `feedback-${comment.id}`;
}

function assessSafety({ rawIntent, message }) {
  if (!VALID_INTENTS.has(rawIntent)) {
    return {
      intent: 'unknown',
      safety: {
        result: 'blocked',
        reason: `Unknown feedback intent: ${rawIntent}.`,
      },
    };
  }

  if (/\brm\s+-rf\b|C:\\Users\\|\/Users\/|host machine/i.test(message)) {
    return {
      intent: rawIntent,
      safety: {
        result: 'blocked',
        reason: 'Feedback asks for direct host execution or destructive filesystem access.',
      },
    };
  }

  return {
    intent: rawIntent,
    safety: {
      result: 'allowed',
      reason: null,
    },
  };
}

function nextActionFor(item) {
  const target = item.targetIssue ? `#${item.targetIssue}` : `goal #${item.activeGoalIssue}`;
  if (item.status === 'blocked') {
    return `Escalate blocked ${item.intent} feedback on ${target}.`;
  }

  return `Apply ${item.intent} feedback to ${target}.`;
}

function compareFeedback(left, right) {
  return String(left.source.createdAt).localeCompare(String(right.source.createdAt));
}

function issueRef(number) {
  return `#${number}`;
}

function formatFeedbackTarget(item) {
  return item.targetIssue ? issueRef(item.targetIssue) : `goal ${issueRef(item.activeGoalIssue)}`;
}

export function createFeedbackIntake(options = {}) {
  const issueClient = options.issueClient ?? null;
  const intake = {
    ingestComments({ activeGoalIssue, comments }) {
      const feedbackItems = comments
        .filter((comment) => String(comment.body ?? '').includes(FEEDBACK_MARKER))
        .map((comment) => {
          const fields = parseFields(comment.body ?? '');
          const rawIntent = fields.intent ?? 'unknown';
          const message = fields.message ?? '';
          const assessed = assessSafety({ rawIntent, message });
          const item = {
            key: feedbackKey(comment),
            source: {
              type: 'github-comment',
              commentId: comment.id,
              url: comment.url,
              author: authorLogin(comment),
              createdAt: comment.createdAt,
            },
            activeGoalIssue,
            targetIssue: parseTargetIssue(fields.target) ?? activeGoalIssue,
            intent: assessed.intent,
            scope: fields.scope ?? 'general',
            message,
            status: assessed.safety.result === 'allowed' ? 'unapplied' : 'blocked',
            safety: assessed.safety,
            nextAction: null,
          };
          item.nextAction = nextActionFor(item);
          return item;
        })
        .sort(compareFeedback);

      const unappliedFeedback = feedbackItems.filter((item) => item.status === 'unapplied');
      const blockedFeedback = feedbackItems.filter((item) => item.status === 'blocked');
      const nextFeedback = unappliedFeedback[0] ?? blockedFeedback[0] ?? null;

      return {
        feedbackItems,
        unappliedFeedback,
        blockedFeedback,
        status: {
          active_goal: activeGoalIssue,
          unapplied_feedback: unappliedFeedback.length,
          blocked_feedback: blockedFeedback.length,
          next_feedback_action: nextFeedback?.nextAction ?? null,
        },
      };
    },

    async ingestFromGithub({ repository, activeGoalIssue, issueNumber = activeGoalIssue }) {
      if (!issueClient?.listComments) {
        throw new Error('GitHub issue client with listComments is required.');
      }

      const comments = await issueClient.listComments({ repository, issueNumber });
      return intake.ingestComments({ activeGoalIssue, comments });
    },

    formatFeedbackStatusComment(result) {
      const queueLines = result.feedbackItems.length > 0
        ? result.feedbackItems.map((item) => (
            `- ${item.key}: ${item.intent} for ${formatFeedbackTarget(item)} - ${item.status}`
          ))
        : ['- none'];

      return [
        '> *This was generated by AI during triage.*',
        '',
        '## MVP feedback status',
        '',
        `- Active goal: ${issueRef(result.status.active_goal)}`,
        `- Unapplied feedback: ${result.status.unapplied_feedback}`,
        `- Blocked feedback: ${result.status.blocked_feedback}`,
        `- Next feedback action: ${result.status.next_feedback_action ?? 'none'}`,
        '',
        'Feedback queue:',
        ...queueLines,
      ].join('\n');
    },
  };

  return intake;
}
